# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='service_app.Ward'),
        ),
        migrations.AlterField(
            model_name='group',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='service_app.Floor'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='service_app.Group'),
        ),
    ]
